//! The rule catalogue: what `reap init --detect` knows how to write.
//!
//! Each entry is the TOML block for one rule, the tool whose presence justifies
//! it, and a sentence saying what it reclaims. `init` emits the blocks whose
//! tool it actually found, so a machine without Xcode does not get a config
//! full of rules that can never match.
//!
//! The same rules, hand-arranged and expanded, are what `examples/` contains.

use std::path::Path;

/// A toolchain whose presence justifies a set of rules.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Stack {
    Rust,
    Node,
    Pnpm,
    Python,
    Uv,
    Xcode,
    Go,
    Gradle,
    Docker,
    Browsers,
    Generic,
}

impl Stack {
    pub fn label(self) -> &'static str {
        match self {
            Stack::Rust => "Rust",
            Stack::Node => "Node",
            Stack::Pnpm => "pnpm",
            Stack::Python => "Python",
            Stack::Uv => "uv",
            Stack::Xcode => "Xcode",
            Stack::Go => "Go",
            Stack::Gradle => "Gradle",
            Stack::Docker => "Docker",
            Stack::Browsers => "Headless browsers",
            Stack::Generic => "Common",
        }
    }
}

/// One rule the catalogue can emit.
pub struct Entry {
    pub stack: Stack,
    pub name: &'static str,
    pub tier: u8,
    /// Platforms this rule is written for. Empty means both.
    pub os: &'static [&'static str],
    /// One line above the rule saying what it reclaims.
    pub comment: &'static str,
    /// The rule body, without the `[[rule]]` header or the `name` line.
    pub body: &'static str,
    /// A root this rule needs in order to match anything, if it is not one of
    /// the user's own code directories. `~`-prefixed.
    pub extra_root: Option<&'static str>,
    /// Depth cap for that extra root.
    pub extra_root_depth: usize,
}

/// Everything `init --detect` knows about.
///
/// Ordered by tier, then by how likely a reader is to recognise it. The order
/// is what a generated config looks like top to bottom.
pub const CATALOG: &[Entry] = &[
    // --- tier 0 -----------------------------------------------------------
    Entry {
        stack: Stack::Generic,
        name: "python-bytecode",
        tier: 0,
        os: &[],
        comment: "Compiled bytecode. Regenerated on the next import.",
        body: "kind = \"path\"\ntier = 0\ndir_name = \"__pycache__\"\nmin_idle = \"1h\"\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Python,
        name: "python-tool-caches",
        tier: 0,
        os: &[],
        comment: "pytest, mypy and ruff caches. Rebuilt on the next run.",
        body: "kind = \"path\"\ntier = 0\nglob = \"**/.{pytest,mypy,ruff}_cache\"\nmin_idle = \"24h\"\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Rust,
        name: "cargo-target",
        tier: 0,
        os: &[],
        comment: "Rust build output. The single biggest win on most developer machines.",
        body: "kind = \"path\"\ntier = 0\ndir_name = \"target\"\n# Only where a Cargo.toml sits beside it, so a directory that merely\n# happens to be called \"target\" is never touched.\nrequire_sibling = \"Cargo.toml\"\nmin_idle = \"48h\"\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Generic,
        name: "coverage-output",
        tier: 0,
        os: &[],
        comment: "Coverage reports. Regenerated by the next test run.",
        body: "kind = \"path\"\ntier = 0\nglob = \"**/{htmlcov,coverage}\"\nmin_idle = \"24h\"\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Go,
        name: "go-build-cache",
        tier: 0,
        os: &[],
        comment: "Go's own build cache, cleaned by Go rather than by removing files.",
        body: "kind = \"command\"\ntier = 0\ncommand = [\"go\", \"clean\", \"-cache\"]\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    // --- tier 1 -----------------------------------------------------------
    Entry {
        stack: Stack::Node,
        name: "node-modules",
        tier: 1,
        os: &[],
        comment: "Installed dependencies. A reinstall costs minutes and bandwidth.",
        body: "kind = \"path\"\ntier = 1\ndir_name = \"node_modules\"\nrequire_sibling = \"package.json\"\nmin_idle = \"14d\"\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Python,
        name: "python-venv",
        tier: 1,
        os: &[],
        comment: "Virtual environments. Recreating one costs a reinstall.",
        body: "kind = \"path\"\ntier = 1\nglob = \"**/{.venv,venv}\"\n# Only inside a repository, so a long-lived environment you keep\n# somewhere else is not swept up.\nrequire_ancestor = \".git\"\nmin_idle = \"30d\"\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Xcode,
        name: "xcode-derived-data",
        tier: 1,
        os: &["macos"],
        comment: "Xcode's build output. Routinely tens of gigabytes, and nothing else here touches it.",
        body: "kind = \"path\"\ntier = 1\nglob = \"~/Library/Developer/Xcode/DerivedData/*\"\nmin_idle = \"48h\"\nos = [\"macos\"]\n",
        extra_root: Some("~/Library/Developer/Xcode/DerivedData"),
        extra_root_depth: 1,
    },
    Entry {
        stack: Stack::Xcode,
        name: "xcode-unavailable-simulators",
        tier: 1,
        os: &["macos"],
        comment: "Simulator runtimes for SDKs you no longer have. Removed by Xcode's own tool.",
        body: "kind = \"command\"\ntier = 1\ncommand = [\"xcrun\", \"simctl\", \"delete\", \"unavailable\"]\nos = [\"macos\"]\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Browsers,
        name: "playwright-browsers",
        tier: 1,
        os: &[],
        comment: "Downloaded browser builds. Re-downloaded on the next install.",
        body: "kind = \"path\"\ntier = 1\nglob = \"~/{Library/Caches/ms-playwright,.cache/ms-playwright}/*\"\nmin_idle = \"30d\"\n",
        extra_root: Some("~/Library/Caches/ms-playwright"),
        extra_root_depth: 1,
    },
    Entry {
        stack: Stack::Docker,
        name: "docker-dangling-images",
        tier: 1,
        os: &[],
        comment: "Image layers no tag refers to any more.",
        body: "kind = \"command\"\ntier = 1\ncommand = [\"docker\", \"image\", \"prune\", \"-f\"]\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    // --- tier 2 -----------------------------------------------------------
    Entry {
        stack: Stack::Rust,
        name: "cargo-registry-cache",
        tier: 2,
        os: &[],
        comment: "Downloaded crate archives. Losing these slows every later build in every project.",
        body: "kind = \"path\"\ntier = 2\nglob = \"~/.cargo/registry/{cache,src}/*\"\nmin_idle = \"60d\"\n",
        extra_root: Some("~/.cargo/registry"),
        extra_root_depth: 2,
    },
    Entry {
        stack: Stack::Pnpm,
        name: "pnpm-store",
        tier: 2,
        os: &[],
        comment: "The shared pnpm content store, pruned by pnpm itself.",
        body: "kind = \"command\"\ntier = 2\ncommand = [\"pnpm\", \"store\", \"prune\"]\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Node,
        name: "npm-cache",
        tier: 2,
        os: &[],
        comment: "npm's cache. `verify` also drops what it cannot use.",
        body: "kind = \"command\"\ntier = 2\ncommand = [\"npm\", \"cache\", \"verify\"]\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Uv,
        name: "uv-cache",
        tier: 2,
        os: &[],
        comment: "uv's wheel cache, pruned by uv itself.",
        body: "kind = \"command\"\ntier = 2\ncommand = [\"uv\", \"cache\", \"prune\"]\n",
        extra_root: None,
        extra_root_depth: 0,
    },
    Entry {
        stack: Stack::Gradle,
        name: "gradle-caches",
        tier: 2,
        os: &[],
        comment: "Gradle's dependency and build caches.",
        body: "kind = \"path\"\ntier = 2\nglob = \"~/.gradle/caches/*\"\nmin_idle = \"60d\"\n",
        extra_root: Some("~/.gradle/caches"),
        extra_root_depth: 1,
    },
    Entry {
        stack: Stack::Docker,
        name: "docker-build-cache",
        tier: 2,
        os: &[],
        comment: "Docker's build cache. Losing it means every later build starts cold.",
        body: "kind = \"command\"\ntier = 2\ncommand = [\"docker\", \"builder\", \"prune\", \"-f\"]\n",
        extra_root: None,
        extra_root_depth: 0,
    },
];

/// Whether an executable of this name is on `PATH`.
pub fn on_path(program: &str) -> bool {
    let Some(path) = std::env::var_os("PATH") else {
        return false;
    };
    std::env::split_paths(&path).any(|dir| dir.join(program).is_file())
}

/// What was found on this machine, and the evidence for it.
#[derive(Debug, Clone)]
pub struct Found {
    pub stack: Stack,
    pub evidence: String,
}

/// Detects the toolchains present on this machine.
///
/// Presence of the tool, or of the directory it keeps its cache in. Both are
/// checked because a machine can have the caches without the binary on `PATH`
/// right now, and a fresh machine can have the binary without the caches.
pub fn detect(home: &Path) -> Vec<Found> {
    let mut found = Vec::new();
    let mut note = |stack: Stack, evidence: String| found.push(Found { stack, evidence });

    // `Generic` rules cost nothing and match on any machine.
    note(Stack::Generic, "always included".to_owned());

    for (stack, programs, dirs) in [
        (Stack::Rust, &["cargo", "rustc"][..], &[".cargo"][..]),
        (Stack::Node, &["node", "npm"][..], &[".npm"][..]),
        (
            Stack::Pnpm,
            &["pnpm"][..],
            &["Library/pnpm", ".local/share/pnpm"][..],
        ),
        (Stack::Python, &["python3", "pip3"][..], &[][..]),
        (
            Stack::Uv,
            &["uv"][..],
            &[".cache/uv", "Library/Caches/uv"][..],
        ),
        (Stack::Go, &["go"][..], &["go/pkg"][..]),
        (Stack::Gradle, &["gradle"][..], &[".gradle"][..]),
        (Stack::Docker, &["docker"][..], &[][..]),
        (
            Stack::Browsers,
            &[][..],
            &[
                "Library/Caches/ms-playwright",
                ".cache/ms-playwright",
                "Library/Caches/puppeteer",
                ".cache/puppeteer",
            ][..],
        ),
    ] {
        // Report the program name rather than where it happens to live: the
        // full path is noise, and on someone else's machine it is different
        // noise.
        if let Some(p) = programs.iter().find(|p| on_path(p)) {
            note(stack, format!("{p} is on PATH"));
            continue;
        }
        if let Some(d) = dirs.iter().find(|d| home.join(d).exists()) {
            note(stack, format!("~/{d} exists"));
        }
    }

    if cfg!(target_os = "macos") && home.join("Library/Developer/Xcode").exists() {
        note(Stack::Xcode, "~/Library/Developer/Xcode exists".to_owned());
    }

    found
}
